name: Create Acceptance PR

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  create-acceptance-pr:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create new branch for acceptance
        run: |
          git switch -c acceptance-update origin/acceptance
          echo "sha: ${{ github.event.pull_request.merge_commit_sha }}"
          git rev-parse HEAD
          git cherry-pick ${{ github.event.pull_request.merge_commit_sha }}

      - name: Push new branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin acceptance-update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Squashed commit from PR #${{ github.event.pull_request.number }}"
          branch: acceptance-update
          base: acceptance
          title: "PR for acceptance: Squashed commit from PR #${{ github.event.pull_request.number }}"
          body: "This PR contains the squashed commit from PR #${{ github.event.pull_request.number }}."
