name: Node

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:

    strategy:
      matrix:
        version: [18, 20, 22]
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
      - name: yarn install
        run: yarn install --frozen-lockfile
      - name: yarn build
        run: yarn build
      - name: yarn coverage
        run: yarn coverage | tail -n +7 >> $GITHUB_STEP_SUMMARY
