name: Node

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: yarn install
        run: yarn install --frozen-lockfile
      - name: yarn build
        run: yarn build
      - name: yarn test
        run: yarn test | tail -n +4 >> $GITHUB_STEP_SUMMARY
